imports:
  - { resource: ./application.yaml }

services:
  Todo.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Todo.Shared.ConnectionManager']